version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              cmake g++ libsfml-dev \
              xvfb libgl1-mesa-dri

      - run:
          name: Build project with CMake
          command: |
            mkdir -p build
            cd build
            cmake ..
            make -j

      - run:
          name: Run headless (virtual display) zonder audio
          command: |
            echo "Running headless with Xvfb + dummy audio..."
            export ALSOFT_DRIVERS=null          # OpenAL: dummy backend (geen echte audio nodig)
            export LIBGL_ALWAYS_SOFTWARE=1      # software rendering (llvmpipe)
            xvfb-run -a -s "-screen 0 1280x720x24" ./build/GhanaJump

      # Als je liever niet faalt wanneer het toch crasht, gebruik dan:
      # - run:
      #     name: Run headless (non-fatal)
      #     command: |
      #       export ALSOFT_DRIVERS=null
      #       export LIBGL_ALWAYS_SOFTWARE=1
      #       xvfb-run -a -s "-screen 0 1280x720x24" ./build/GhanaJump || echo "Program exited (OK on CI)"